name: ricenetwork
version: 1.0.0+1
dependencies:
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: Druk
      fonts:
        - asset: assets/fonts/Druk-Bold.ttf
