name: Build iOS
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
      - name: Check Flutter version
        run: flutter --version
      - name: Get dependencies
        run: flutter pub get
      - name: Create iOS platform
        run: flutter create --platforms=ios .
      - name: Build IPA
        run: flutter build ipa --debug --no-codesign
      - name: Check IPA output
        run: ls -la build/ios/ipa/ || echo "No IPA directory found"
      - uses: actions/upload-artifact@v4
        with:
          name: ricenetwork-ipa
          path: build/ios/ipa/*.ipa
          if-no-files-found: warn
