name: Build iOS
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter create --platforms=ios .  # На случай, если ios/ битая
      - run: flutter build ipa --debug
      - uses: actions/upload-artifact@v3
        with:
          name: ricenetwork-ipa
          path: build/ios/ipa/*.ipa